# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(max_length=3)),
                ('img', models.ImageField(upload_to='images')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkstand.Kind')),
            ],
        ),
    ]
