# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('qr_coder', models.ImageField(upload_to='desks')),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='menus')),
                ('state', models.BooleanField()),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkstand.Kind')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(max_length=200)),
                ('totle_price', models.IntegerField()),
                ('state', models.BooleanField()),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkstand.Desk')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkstand.Menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkstand.Order')),
            ],
        ),
    ]
