# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('time', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('remark', models.CharField(max_length=200)),
                ('desk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Desk')),
            ],
        ),
    ]
